### PR TITLE
feat: allow for quiz exports to handle images

### PR DESCRIPTION
**Pull request by tomwisecodes**
## Description

This allows for all of our doc exports to be able to handle export images. This work precedes the maths quiz questions work which will call on oak maths questions where the questions and answers are often in image form. The logic may also be reused in the future for adding images to slides.

How to test:
In order to test this run through the download process for a quiz and it should work with no changes

### CODE REVIEW

**Review by mikeritson-oak — CHANGES_REQUESTED** [review]
I've done some initial tests in Chrome and getting varying results when trying to export the resources.

- First lesson, new, failed to export warnings on all
- Second lesson, old, selected items downloaded
- First lesson (retry), some downloaded then warnings again

 The warnings/failures seem sporadic, some generate/download, others fail. No errors or warnings seen in the console at time of download.
  
SCR-20241113-klqj
SCR-20241113-kgzb

**Comment by mantagen** [comment]
@tomwisecodes I think importantly for this work to go in, we need it to be able to handle markdown inline in questions or answers/distractors:

```js
{
          question:
            "Complete the statement. Triangle ABC and triangle XYZ are ____________. ![image](http://oaknationalacademy-res.cloudinary.com/image/upload/v1706110974/fukcqeavzcevgjhmm1n4.png)",
          answers: ["similar as the three interior angles are the same."],
          distractors: [
            "congruent as the three interior angles are all the same.",
            "neither similar nor congruent.",
          ],
        }
```

**Review by mantagen — APPROVED** [review]
Works well!

**Comment by mantagen** [comment]
Closing in favour of https://github.com/oaknational/oak-ai-lesson-assistant/pull/400

**Pull request closed without merging**
